---
title: "Mensch & Umwelt"
---

Der Mensch und die Umwelt profitieren gleichermaßen durch die neuerstandenen innerstädtischen Freiflächen in Folge des Strukturwandels im Ruhrgebiet. 

Den Industriewäldern im Ruhrgebiet werden im ökologischen Sinne einen hohen Nutzen zugesprochen, wodurch den Folgen des Klimawandels entgegengewirkt werden können. Insbesondere durch die Freiflächen, in dem sonst so dicht bebauten Ruhrgebiet, entstehen an dieser Stelle zahlreiche positive Auswirkungen: Bei Starkregenereignissen kann das Wasser in den Waldboden aufgenommen und gespeichert werden und entlastet somit das städtische Abwassersystem. Die Vegetation nimmt Wasser auf und sorgt durch die Verdunstung an warmen Sommermonaten für eine deutliche Absenkung der Temperatur. Zudem heizt sich Waldfläche im Vergleich zu einer betonierten Straße wesentlich schwächer auf. Durch diese Temperaturunterschiede können sich abkühlende Frischluft-Winde bilden, die Hitzeinseln in den Städten auflösen. Je nach Größe und Lage der Freifläche, kann dieses Phänomen stark variieren.

Neben den ökologischen Folgen, stellen die neuerstandenen Wälder Erholungsgebiete mit einer hohen Freizeitfaktor für die Bevölkerung dar. Neben Tätigkeiten wie sportlichen Aktivitäten oder als Ort zum Verweilen und zum Begegnen, werden die Wälder zudem zu pädagogischen Zwecken genutzt: Der Wandel von einer montanindustriell-geprägten Fläche hin zu einem ökologisch – jungen – und einzigartigen Naturraum mit einer hohen Biodiversität, begeistern dabei Jung und Alt. So werden verschiedene waldpädagogische Aktivitäten auf den jeweiligen Internetplattformen der Industriewälder angeboten.
